using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Mail;
using LRCA.classes;
using LRCA.classes.Entity;
using LRCA.classes.DAL;
using System.Net;

public class Mailing
    {
        public static string GetSMTP()
        {
            string SMTP = "sm14.internetmailserver.net";
            return SMTP;
        }
        public static string SenderEmail()
        {
           // string SenderEmail = "postmaster@serigorproducts.com" ;
            string SenderEmail = "";
            return SenderEmail;
        }
        public static string SenderEmailPass()
        {
           // string SenderEmailPass = "";
            string SenderEmailPass = "";
            return SenderEmailPass;
        }
        public static string SMTPPort()
        {
            //string SMTPPort = "587";
            string SMTPPort = "25";
            return SMTPPort;
        }
        public static void SendMailNotice(string Title, string emails, string Message, string CompanyName)
        {

            System.Text.StringBuilder bodytext = new System.Text.StringBuilder();
            //bodytext.AppendLine("Siva,");
            bodytext.AppendLine("New notice from " + CompanyName + Environment.NewLine);
            //bodytext.AppendLine("His email is: " + email + Environment.NewLine);
            bodytext.AppendLine("Message: " + Message + Environment.NewLine);
            bodytext.AppendLine(Environment.NewLine + Environment.NewLine + Environment.NewLine);
            bodytext.AppendLine("This message is generated by https://lrca20200812173447.azurewebsites.net/default.aspx#login. Please, DO NOT REPLY!" + Environment.NewLine);


            MailAddress senderAddress = new MailAddress("postmaster@serigorproducts.com" );
           
            MailMessage mail = new MailMessage();
            mail.From = senderAddress;
            mail.To.Add(emails.ToString());
            mail.IsBodyHtml = false;
            mail.Subject = CompanyName + " Notice: " + Title;
            mail.Body = bodytext.ToString();
            mail.Priority = MailPriority.Normal;
            SendEmailAsh(mail);

        }

        public static void SendContactMailITHelp(string Company, string Branch, string IssueType, string name, string email, string Message, string UserIP)
    {
        try
        {
            System.Text.StringBuilder bodytext = new System.Text.StringBuilder();
            bodytext.AppendLine("IT HELP!");
            bodytext.AppendLine("New inquery has been generated By " + name + Environment.NewLine);
            bodytext.AppendLine("His Email is: " + email + Environment.NewLine);
            bodytext.AppendLine("Company " + Company + Environment.NewLine);
            bodytext.AppendLine("Branch " + Branch + Environment.NewLine);
            bodytext.AppendLine("Problem Type " + IssueType + Environment.NewLine);
            bodytext.AppendLine("Message " + Message + Environment.NewLine);
            bodytext.AppendLine("User IP Address: " + UserIP + Environment.NewLine);

            //MailAddress senderAddress = new MailAddress(email);
            
            MailAddress senderAddress = new MailAddress("postmaster@serigorproducts.com" );
            MailAddress recipAddress = new MailAddress("postmaster@serigorproducts.com" );
            MailMessage mail = new MailMessage(senderAddress, recipAddress);

            mail.IsBodyHtml = false;
            mail.Subject = "IT Issue reported by " + name + " / " + Company;
            mail.Body = bodytext.ToString();
            mail.Priority = MailPriority.Normal;
            SendEmailAsh(mail);
        }
        catch(Exception ex)
        {
            
        }

       

    }

        public static void SendContactMail(string name, string email, string Message, string UserIP)
        {
        
                System.Text.StringBuilder bodytext = new System.Text.StringBuilder();
                bodytext.AppendLine("Siva,");
                bodytext.AppendLine("New inquery has been generated By "+ name + Environment.NewLine);
                bodytext.AppendLine("His/Her email is: " + email + Environment.NewLine);
                bodytext.AppendLine("Message: " + Message + Environment.NewLine);
                bodytext.AppendLine("User IP Address: " + UserIP + Environment.NewLine);
            

                MailAddress senderAddress = new MailAddress(email);
                MailAddress recipAddress = new MailAddress("postmaster@serigorproducts.com" );
                MailMessage mail = new MailMessage(senderAddress, recipAddress);
                
                mail.IsBodyHtml = false;
                mail.Subject = " Inquiry request by " + name ;
                mail.Body = bodytext.ToString();
                mail.Priority = MailPriority.Normal;
                SendEmailAsh(mail);
           
        }
        public static void SendWelcomeMail(clsUser objEmp, string email, string TempPass)
        {
        
        System.Text.StringBuilder bodytext = new System.Text.StringBuilder();
        //clsUser objEmp = new clsUser();
        //objEmp = UserDAL.SelectUserById(Convert.ToInt32(EmployeeId));
        if (objEmp != null)
        {
            bodytext.AppendLine("Dear " + objEmp.FName + " " + objEmp.LName + "," + Environment.NewLine);
            bodytext.AppendLine("Congratulations your new account has been created on LRCA. To login please click on  https://lrca20200812173447.azurewebsites.net/default.aspx#login" + Environment.NewLine);
            //bodytext.AppendLine("");
            bodytext.AppendLine("Enter your registered email and Temporary Password as shown below." + Environment.NewLine);
            bodytext.AppendLine("Your registered email: " + objEmp.EmailId);
            bodytext.AppendLine("Your Temporary Password: " + TempPass + Environment.NewLine);
            bodytext.AppendLine("If you have any questions please contact us at postmaster@serigorproducts.com or call us at 301-333-3333" + "");
            bodytext.AppendLine("");
            bodytext.AppendLine("Thank you,");
            bodytext.AppendLine("LRCA Support Team");
        }
        MailAddress senderAddress = new MailAddress("postmaster@serigorproducts.com" );
        MailAddress recipAddress = new MailAddress(email);
        MailMessage mail = new MailMessage(senderAddress, recipAddress);
       
        mail.IsBodyHtml = false;
        mail.Subject = " Your LRCA account Information " + GlobalMethods.stringToMixedCase(objEmp.FName + " " + objEmp.LName);
        mail.Body = bodytext.ToString();
        mail.Priority = MailPriority.Normal;
        SendEmailAsh(mail);

    }
        public static void Send30daysMail(string name, string email, string phone, string Company, string UserIP, string Companywebsite)
        {

            System.Text.StringBuilder bodytext = new System.Text.StringBuilder();
            bodytext.AppendLine("Siva,");
            bodytext.AppendLine("New inquery has been generated by " + name + " to setup a 30 days free trial. "+ Environment.NewLine);
            bodytext.AppendLine("His email is: " + email + Environment.NewLine);
            bodytext.AppendLine("phone: " + phone + Environment.NewLine);
            bodytext.AppendLine("Company: " + Company + Environment.NewLine);
            bodytext.AppendLine("User IP Address: " + UserIP + Environment.NewLine);
            bodytext.AppendLine("Company Website: " + Companywebsite + Environment.NewLine);

            MailAddress senderAddress = new MailAddress(email);
            MailAddress recipAddress = new MailAddress("postmaster@serigorproducts.com" ,"irfan.khan@LRCA.com");
            MailMessage mail = new MailMessage(senderAddress, recipAddress);

            mail.IsBodyHtml = false;
            mail.Subject = " 30 days free trial requested by " + name;
            mail.Body = bodytext.ToString();
            mail.Priority = MailPriority.Normal;
            SendEmailAsh(mail);

        }
        public static void SendCloseAccount(string name, string email, string Company)
        {

            System.Text.StringBuilder bodytext = new System.Text.StringBuilder();
            bodytext.AppendLine("Siva,");
            bodytext.AppendLine("Request has been generated by  " + name + " to close account for " + Company + " " + Environment.NewLine);
            bodytext.AppendLine("His email is: " + email + Environment.NewLine);
            bodytext.AppendLine("Company: " + Company + Environment.NewLine);
            
            MailAddress senderAddress = new MailAddress(email);
            MailAddress recipAddress = new MailAddress("postmaster@serigorproducts.com");
            MailMessage mail = new MailMessage(senderAddress, recipAddress);

            mail.IsBodyHtml = false;
            mail.Subject = " Request to CLOSE ACCOUNT: " + Company;
            mail.Body = bodytext.ToString();
            mail.Priority = MailPriority.Normal;
            SendEmailAsh(mail);

        }
        public static void SendResetPasswordMail(string EmployeeId, string email, string TempPass)
        {
        System.Text.StringBuilder bodytext = new System.Text.StringBuilder();
        clsUser objEmp = new clsUser();
        objEmp = UserDAL.SelectUserById(Convert.ToInt32(EmployeeId));
        if (objEmp!=null)
        {
            bodytext.AppendLine("Dear " + objEmp.FName+ " " + objEmp.LName + ",");
            bodytext.AppendLine("Your Password has been reset!");
            bodytext.AppendLine("Please goto https://lrca20200812173447.azurewebsites.net/default.aspx#login");
            bodytext.AppendLine("You will find your registered Email and Temporary Password below.");
            bodytext.AppendLine("");
            bodytext.AppendLine("Your registered email: " + objEmp.EmailId);
            bodytext.AppendLine("Your Temporary Password: " + TempPass + Environment.NewLine);
            bodytext.AppendLine("");
            bodytext.AppendLine("If you have any questions please contact us at postmaster@serigorproducts.com or call us at 301-333-3333" + "");
            bodytext.AppendLine("");
            bodytext.AppendLine("Thank you,");
            bodytext.AppendLine("");
            bodytext.AppendLine("LRCA Support Team");

        }
        MailAddress senderAddress = new MailAddress("postmaster@serigorproducts.com" );
        MailAddress recipAddress = new MailAddress(email);
        MailMessage mail = new MailMessage(senderAddress, recipAddress);
        mail.IsBodyHtml = false;
        mail.Subject = " Your LRCA account Information " + GlobalMethods.stringToMixedCase(objEmp.FName + " " + objEmp.LName);
        mail.Body = bodytext.ToString();
        mail.Priority = MailPriority.Normal;
        SendEmailAsh(mail);

    }
        public static void SendEmail(MailMessage email)
        {
            try
            {
            SmtpClient smtp = new SmtpClient("sm14.internetmailserver.net");
            //Enter your full e-mail address and password
            smtp.Credentials = new NetworkCredential("postmaster@serigorproducts.com", "@s3r1G0r#");
            smtp.Port = Convert.ToInt32("25");
            smtp.EnableSsl = false;
            //send the message 
            smtp.Send(email);
           
        }
            catch(Exception)
            {
             //   SendEmail(email);
            }
            
        }
        public static void SendEmailAsh(MailMessage email)
        {

       


        try
            {
            SmtpClient smtp = new SmtpClient("sm14.internetmailserver.net");
            //Enter your full e-mail address and password
            smtp.Credentials = new NetworkCredential("postmaster@serigorproducts.com", "@s3r1G0r#");
            smtp.Port = Convert.ToInt32("25");
            smtp.EnableSsl = false;
            //send the message 
            smtp.Send(email);
            // SmtpClient smtpServer = new SmtpClient();
            // smtpServer.Host = "smtp.ionos.com";
            // smtpServer.Credentials = new System.Net.NetworkCredential("postmaster@serigorproducts.com" , "Census$6301996");
            // smtpServer.Port = Convert.ToInt32("25");
            //// smtpServer.EnableSsl = true;
            // smtpServer.Send(email);
        }
            catch (Exception ex)
            {
                SendEmail(email);
            }
            
        }

    }
